-- 코드를 입력하세요
SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, ( FP.PRICE * SUM(FO.AMOUNT) ) as TOTAL_SALES
    FROM FOOD_PRODUCT FP
    LEFT JOIN FOOD_ORDER FO
        on FP.PRODUCT_ID = FO.PRODUCT_ID
            WHERE FO.PRODUCE_DATE LIKE '2022-05%'
                GROUP BY FP.PRODUCT_ID 
                    ORDER BY TOTAL_SALES DESC, FP.PRODUCT_ID ASC